name: "gcs"
version: "0.2.1"
usage: "This plugin allows to use gcs protocol to upload, fetch charts and to work with repositories."
description: |-
  Provides Google Cloud Storage protocol support.
  https://github.com/tbro/helm-gcs
command: "$HELM_PLUGIN_DIR/bin/gcs-helper.sh"
downloaders:
- command: "bin/gcs-repo.sh"
  protocols:
    - "gs"
